owner: roozbehzarei
repo: filester-status

sites:
  - name: Oshi
    url: https://oshi.at
  - name: transfer.sh
    url: https://transfer.sh

status-website:
  theme: light
  css: "nav { display: none }"
  favicon: https://raw.githubusercontent.com/roozbehzarei/filester-status/master/assets/favicon.png
  faviconSvg: https://raw.githubusercontent.com/roozbehzarei/filester-status/1262fc8402b1541603097532c99ff9dbdcc2ffa7/assets/favicon.svg
  baseUrl: /filester-status
  logoUrl: https://raw.githubusercontent.com/roozbehzarei/filester-status/master/assets/logo.webp
  name: Filester

i18n:
  footer: Powered by Upptime.
